version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  test:
    docker:
      - image: cimg/node:16.20.2

    working_directory: ~/repo

    steps:
      - checkout

      - node/install-packages:
                pkg-manager: yarn

      - run:
          name: Test
          command: yarn test


workflows:
  suite:
    jobs:
      - test
